## Topics

## 1. Many Choices for the Activation Function
## 2. Simple Multi-layer Neural Network

<br>
<br>



## 1. Comparison of the different activation functions:

## (https://en.wikipedia.org/wiki/Activation_function, and there are more)

Logistic (a.k.a. Soft step, sigmoid) Activation: $f(x)=\frac{1}{1+e^{-x}}$, $\,f'(x)=f(x)(1-f(x))$,    ($0$, $1$)

TanH Activation: $f(x)=\tanh(x)=\frac{2}{1+e^{-2x}}-1$,	$\,f'(x)=1-f(x)^2$,   ($-1$, $1$)

In [1]:
%matplotlib inline
# All imports
from random import choice
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(formatter={'float': '{:.4f}'.format})


In [2]:
def sigmoid(x):
    '''
    Used in forward propogration
    The logistic function as the sigmoid
    '''

    return 1.0/(1.0 + np.exp(-x))

def sigmoid_pr(z):
    '''
    Used in backprop
    derivative of the logistic function
    '''
    return z * (1 - z)

## The Transpose

In [3]:
M = np.random.rand(3, 2)
print(M)
print(M.shape)
print('Transposed:\n', M.T)
print(M.T.shape)

[[0.6970 0.8287]
 [0.5143 0.4960]
 [0.0878 0.2556]]
(3, 2)
Transposed:
 [[0.6970 0.5143 0.0878]
 [0.8287 0.4960 0.2556]]
(2, 3)


## Note that 

`np.dot()`

## does matrix multiplication for arrays, whether it's actually a dot product
## Below are a few examples:

## An example of np.dot for (2, 3) matrices, use integers as matrix elements

In [4]:
np.dot(np.array([1, 2]), np.array([3, 4]))

11

In [8]:
A = np.arange(6)
print(A)
A = A.reshape(2, 3)
print(A)

b = np.arange(3)/2
print(b)

R = np.dot(A, b)
print(A.shape)
print(b.shape)
print(R)
b[0]

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0.0000 0.5000 1.0000]
(2, 3)
(3,)
[2.5000 7.0000]


0.0

In [7]:
np.dot(b, A)

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

In [50]:
b = b.reshape(1, 3)
print(b.shape)
c = (np.arange(3)/3).reshape(3, 1)
print(c.shape)
print(b)
print(c)
b[0][1]

(1, 3)
(3, 1)
[[0.0000 0.5000 1.0000]]
[[0.0000]
 [0.3333]
 [0.6667]]


0.5

In [52]:
np.dot(b, c), np.dot(c, b)

(array([[0.8333]]),
 array([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.1667, 0.3333],
        [0.0000, 0.3333, 0.6667]]))

## Breakout Excercise -- Write a function forwardprop(X, w0, w1) that performs the forward propagation

   - ## X is the input array
   - ## w0 are the weights in the first layer (it should be a 2x2 array...and think dot product)
   - ## w1 are the weights for the second layer (it has 2 weights)
   - ## It should return z, b, A, a
   - ## Test it with the input values and weights given in lecture.  And then print out the following, and make sure they agree to at least 7th decimal place:
   
            X = [0.35, 0.9]  
 
            w0:
             [[0.1000 0.4000]
             [0.8000 0.6000]]
            w1:
             [0.3000 0.9000]
            a: [0.7550 0.6800]
            A: [0.6803 0.6637]
            b: 0.801444986674
            output (z) of nn: 0.690283492908 

In [91]:
def forwardprop(x, w0, w1):
    # X = np.append(X, 1) # add bias term
    # z1 = x @ w0
    z1 = np.dot(x, w0)
    a1 = sigmoid(z1)
    # z2 = a1 @ w1
    z2 = np.dot(a1, w1)
    output = sigmoid(z2)
    return z1, a1, z2, output

In [92]:
X = np.array([0.35, 0.9])
print(X.shape)
w0 = np.array([[0.1000, 0.4000], [0.8000, 0.6000]])
print(w0.shape)
w1 = np.array([0.3000, 0.9000])
a, A, b, output = forwardprop(X, w0, w1)
print(f"a: {a}")
print(f"A: {A}")
print(f"b: {b}")
print(f"outputc(z) of nn: {output}")

(2,)
(2, 2)
a: [0.7550 0.6800]
A: [0.6803 0.6637]
b: 0.8014449866735119
outputc(z) of nn: 0.6902834929076443


## np.atleast_2d()

In [53]:
c = np.array([5, 8])
C = np.atleast_2d(c)
print('Vector:\n', c, c.shape)
print('Matrix:\n', C, C.shape)
print('Matrix transposed:\n', C.T, C.T.shape)
print("For a 1-D object, transpose doesn't change anything:", c.T)

Vector:
 [5 8] (2,)
Matrix:
 [[5 8]] (1, 2)
Matrix transposed:
 [[5]
 [8]] (2, 1)
For a 1-D object, transpose doesn't change anything: [5 8]


## The inner (dot) product and the outer product of two vectors

In [55]:
C = np.atleast_2d(np.array([1, 2]))
D = np.atleast_2d(np.array([3, 4]))

# print(A)
# print(B.T)

inner_prod = np.dot(C, D.T)
print("Inner product -- tensor rank goes down by 1") # 1D -> scalar
print("first matrix:", C.shape)
print("second matrix:", D.T.shape)

print('inner product:', inner_prod, inner_prod.shape)

print()

print("Outer Product -- tensor rank goes up by 1") # 1D -> 2D
print("first matrix:", D.T.shape)
print("second matrix:", C.shape)

outer_prod = np.dot(D.T, C)

print('C transposed:\n', C.T)
print('D:', D)
print('outer product:\n', outer_prod)

print()

print('Element by element multiplication -- preserves the the rank of the tensor')
print('element by element multiplication:', C * D)

Inner product -- tensor rank goes down by 1
first matrix: (1, 2)
second matrix: (2, 1)
inner product: [[11]] (1, 1)

Outer Product -- tensor rank goes up by 1
first matrix: (2, 1)
second matrix: (1, 2)
C transposed:
 [[1]
 [2]]
D: [[3 4]]
outer product:
 [[3 6]
 [4 8]]

Element by element multiplication -- preserves the the rank of the tensor
element by element multiplication: [[3 8]]


## Partial Derivatives of $P$ w.r.t. $W^{(0)}_{ij}$, where $i, j = 0$ or $1$.

## Remember: The index of $x_i$ refers to the inputs and the index of $\mathrm{delta1}_j$ refers to the neurons in layer 1.

## $\frac {\partial P} {\partial W^{(0)}_{00}}$ = $x_0$ $\mathrm{delta1}_0$

## $\frac {\partial P} {\partial W^{(0)}_{01}}$ = $x_0$ $\mathrm{delta1}_1$

## $\frac {\partial P} {\partial W^{(0)}_{10}}$ = $x_1$ $\mathrm{delta1}_0$

## $\frac {\partial P} {\partial W^{(0)}_{11}}$ = $x_1$ $\mathrm{delta1}_1$

## This is the *outer* product of $\vec{x}$ and $\overrightarrow{\mathrm{delta1}}$.  This makes sense because there are four weights to be adjusted.

## Breakout Excercise -- Write a function 

`backprop(X, y, z, w0, w1)`

## that performs the backward propagation

   - ## The function should return the updated weights, w0 and w1
   - ## y is the target (= 0.5 in our case)
   - ## Define delta1 as we talked about in lecture
   - ## Also for convenience and clarity, define delta_w1 = delta1 * A.  This is essentially how w1 should be adjusted (with alpha = 1).
   - ## Then define delta1 as we talked about in class -- think about the best way to do it 
   - ## Define a delta_w0.   This is essentially how w0 should be adjusted (with alpha = 1). (*Hint*: Think matrix multiplication.)
   - ## Run it and you should get this:
 

            w0:
             [[0.1000 0.4000]
             [0.8000 0.6000]]
            w1:
             [0.3000 0.9000]
            output (z) of nn: 0.690283492908
            
   - ## For diagnostic purposes:
   
            delta1: -0.04068112511233903
            delta_w1: [-0.0277 -0.0270]
            w1: [0.2723 0.8730]

            sigmoid_pr(A): [0.6803 0.6637]
            delta0: [[-0.0024 -0.0079]]
            delta_w0:
            [[-0.0008 -0.0028]
             [-0.0022 -0.0071]]
            w0:
            [[0.0992 0.3972]
             [0.7978 0.5929]]

In [93]:
def backprop(X, y, z, w0, w1, verbose=False):
    g2_prime = z * (1 - z)
    delta1 = (y - z) * g2_prime
    delta_w1 = delta1 * A
    w1 = w1 + delta_w1
    delta0 = np.atleast_2d(sigmoid_pr(A) * delta1 * w1)
    # delta0 dimension: (hidden_dim, 1)
    # X dimension: (1, input_dim)
    # We want the delta weights to be in the same dimension of original weight, so we must do X.T @ delta0
    delta_w0 = np.atleast_2d(X).T @ delta0
    w0 += delta_w0

    if verbose:
        print(delta1)
        print(delta_w1)
        print(w1)
        print(delta0)
        print(delta_w0)
        print(w0)

In [94]:
backprop(X, y=0.5, z=output, w0=w0, w1=w1, verbose=True)

-0.04068112511233903
[-0.0277 -0.0270]
[0.2723 0.8730]
[[-0.0024 -0.0079]]
[[-0.0008 -0.0028]
 [-0.0022 -0.0071]]
[[0.0992 0.3972]
 [0.7978 0.5929]]


## Breakout Exercise: trains once -- do backward propagation, and then forward prop again to get the first trained output

In [97]:
n = 1
z = 0
X = np.array([0.35, 0.9])
w0 = np.array([[0.1000, 0.4000], [0.8000, 0.6000]])
w1 = np.array([0.3000, 0.9000])
for _ in range(n):
    a, A, b, z = forwardprop(X, w0, w1)
    backprop(X, 0.5, z, w0, w1)
print(z)

0.6902834929076443


## Breakout Exercise: Starting from the initial values of w0 and w1, iterate forward propagation and backward propagation 100 times

In [96]:
n = 100
z = 0
X = np.array([0.35, 0.9])
w0 = np.array([[0.1000, 0.4000], [0.8000, 0.6000]])
w1 = np.array([0.3000, 0.9000])
for _ in range(n):
    a, A, b, z = forwardprop(X, w0, w1)
    backprop(X, 0.5, z, w0, w1)
print(z)

0.6516673537175093


# The End