In [1]:
import numpy as np
np.array([1,2,3])                  # from list
np.zeros(5)                        # 1D zeros
np.ones((2,3))                     # 2x3 ones
np.full((3,3), 7)                  # filled with 7
np.empty((2,2))                    # uninitialized (don’t rely on values)
np.arange(0, 10, 2)                # 0..8 step 2
np.linspace(0, 1, 5)               # 5 evenly spaced in [0,1]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
a.dtype, a.shape, a.ndim, a.size


Pratice quiz

In [3]:
import numpy as np
arr = np.arange(0, 21, 5)
print(arr)
# [ 0  5 10 15 20 ]


[ 0  5 10 15 20]


In [5]:
x = np.arange(12).reshape(3,4)
row2 = x[1]
# [4 5 6 7]
print(row2)


[4 5 6 7]


In [7]:
A = np.arange(16).reshape(4,4)
A[:, -1:]  
# shape (4,1) with values [[3],[7],[11],[15]]


array([[ 3],
       [ 7],
       [11],
       [15]])

In [8]:
x = np.array([2, 5, 8, 11, 14])
x[x > 7]
# [ 8 11 14 ]


array([ 8, 11, 14])

In [9]:
X = np.array([[1,2,3],[4,5,6]])
X_centered = X - X.mean(axis=1, keepdims=True)

In [11]:
M = np.arange(9).reshape(3,3)
M.sum(axis=0)

array([ 9, 12, 15])

In [ ]:
np.arange(9).reshape(3,3)

In [12]:
x = np.arange(10)
x[::2]

array([0, 2, 4, 6, 8])

In [13]:
arr = np.array([4, 7, 10, 13, 16])
arr[arr > 8]

array([10, 13, 16])

In [14]:
y = np.arange(12)
y = np.arange(12).reshape(4,3)
y[-1]         # [9 10 11]


array([ 9, 10, 11])